export const premiumFunctions = [
  {
    field: 'charactername',
    imageSrc: 'premiumstandard',
    headerName: 'Konto Premium 7d',
    description: [
      'Lista dostępnych funkcji w koncie premium może ulec zmianie, w takim przypadku wzbgogacisz się o nowe funkcje bez potrzeby dodatkowego zakupu.',
      '- Darmowe rozmowy telefoniczne',
      '- Darmowe paliwo',
      '- Czat donatorów',
      '- Dodatkowa ilość punktów premium co godzine gry',
      '- Unikalny wybór postaci',
      '- Automatyczne otwieranie bramek przejazdowych bez potrzeby klikania',
    ],
    price: 100,
  },
  {
    field: 'charactername',
    imageSrc: 'premiumgold',
    headerName: 'Konto Premium 30d',
    description: [
      'Lista dostępnych funkcji w koncie premium może ulec zmianie, w takim przypadku wzbgogacisz się o nowe funkcje bez potrzeby dodatkowego zakupu.',
      '- Darmowe rozmowy telefoniczne',
      '- Darmowe paliwo',
      '- Czat donatorów',
      '- Dodatkowa ilość punktów premium co godzine gry',
      '- Unikalny wybór postaci',
      '- Automatyczne otwieranie bramek przejazdowych bez potrzeby klikania',
    ],
    price: 300,
  },
  {
    field: 'charactername',
    imageSrc: 'znizka',
    headerName: 'Karta zniżkowa',
    description: [
      'Karta zniżkowa to specjalny dokument lub kod, który upoważnia do otrzymywania rabatów w sklepach partnerskich.',
      'Karta zniżkowa oznacza, że jej posiadacz może skorzystać z 20% obniżki cenowej na wszystkie produkty w sklepach biorących udział w programie.',
    ],
    price: 50,
  },
  {
    field: 'charactername',
    imageSrc: 'pakiettani',
    headerName: 'Paczka obiektów L',
    description: 'Paczka obiektów - 5 to możliwość postawienia pięciu doniczek w grze, które są potrzebne do siania marihuany.',
    price: 50,
  },
  {
    field: 'charactername',
    imageSrc: 'pakietsredni',
    headerName: 'Paczka obiektów XL',
    description: 'Paczka obiektów - 10 to możliwość postawienia dziesięciu doniczek w grze, które są potrzebne do siania marihuany.',
    price: 100,
  },
  {
    field: 'charactername',
    imageSrc: 'pakietpremium',
    headerName: 'Paczka obiektów XXL',
    description: 'Paczka obiektów - 10 to możliwość postawienia dziesięciu doniczek w grze, które są potrzebne do siania marihuany.',
    price: 100,
  },
  {
    field: 'charactername',
    imageSrc: 'pakietpremium', //do zrobienia
    headerName: 'Własne radio',
    description: ['Zakup własnego radia umożliwia stworzenie stacji radiowej na serwerze, którą kontroluje właściciel.', 'Dzięki niej można włączyć dowolną muzykę, warto dodać, że należy najpierw posiadać swój serwis z taką stacją.'],
    price: 150,
  },
  {
    field: 'charactername',
    imageSrc: 'przeniesieniemajatku',
    headerName: 'Przeniesienie majątku',
    description: 'Funkcja ta, pozwala przenieść wszystkie przedmioty, nieruchomości oraz pojazdy z jednej postaci na drugą.',
    price: 100,
  },
  {
    field: 'charactername',
    imageSrc: 'customintek',
    headerName: 'Niestandardowy interior',
    description: ['Zakup tej funkcji umożliwia zastąpienie domyślnego interioru twoim własnym.', 'Pamiętaj, że musisz mieć swój interior, będziesz mógł ustawić interior tylko raz!'],
    price: 150,
  },
];
